(function () {
  "use strict";

  const verifiedOn = "2026-07-23";

  window.TRADEMATH_EXCHANGES = {
    binance: {
      id: "binance",
      name: "Binance USDⓈ-M",
      settlement: "USDT",
      verifiedOn,
      maintenanceMargin: 0.4,
      fundingFetch: "binance",
      source: "https://www.binance.com/en/fee/futureFee",
      sourceLabel: "Binance USDⓈ-M fee schedule",
      tiers: [
        { id: "standard", label: "Standard / VIP 0", maker: 0.02, taker: 0.05 },
        { id: "bnb", label: "BNB fee discount (verify eligibility)", maker: 0.018, taker: 0.045 },
      ],
    },
    bybit: {
      id: "bybit",
      name: "Bybit USDT Perp",
      settlement: "USDT",
      verifiedOn,
      maintenanceMargin: 0.5,
      source: "https://www.bybit.com/en/help-center/article/?id=000001584",
      sourceLabel: "Bybit perpetual & futures fees",
      tiers: [
        { id: "standard", label: "Non-VIP", maker: 0.02, taker: 0.055 },
        { id: "mnt", label: "MNT payment discount (verify eligibility)", maker: 0.018, taker: 0.0495 },
      ],
    },
    okx: {
      id: "okx",
      name: "OKX USDT-M",
      settlement: "USDT",
      verifiedOn,
      maintenanceMargin: 0.4,
      source: "https://www.okx.com/en-us/help/how-to-calculate-the-contract-transaction-fee",
      sourceLabel: "OKX contract fee calculation",
      tiers: [{ id: "standard", label: "Level 1", maker: 0.02, taker: 0.05 }],
    },
    gate: {
      id: "gate",
      name: "Gate.io USDT Perp",
      settlement: "USDT",
      verifiedOn,
      maintenanceMargin: 0.5,
      source: "https://www.gate.com/help/futures/futures_logic/22079",
      sourceLabel: "Gate futures fee calculation",
      tiers: [{ id: "standard", label: "Standard (verify account)", maker: 0.02, taker: 0.05 }],
    },
    bitget: {
      id: "bitget",
      name: "Bitget USDT-M",
      settlement: "USDT",
      verifiedOn,
      maintenanceMargin: 0.4,
      source: "https://www.bitget.com/support/articles/12560603817155",
      sourceLabel: "Bitget futures fee guide",
      tiers: [{ id: "standard", label: "Non-VIP", maker: 0.02, taker: 0.06 }],
    },
    mexc: {
      id: "mexc",
      name: "MEXC USDT-M",
      settlement: "USDT",
      verifiedOn,
      maintenanceMargin: 0.4,
      source: "https://www.mexc.com/fee",
      sourceLabel: "MEXC trading fee page",
      tiers: [
        { id: "standard", label: "Web/App standard (region may vary)", maker: 0, taker: 0.02 },
        { id: "mx", label: "MX discount (verify eligibility)", maker: 0, taker: 0.01 },
      ],
    },
    hyperliquid: {
      id: "hyperliquid",
      name: "Hyperliquid Perps",
      settlement: "USDC",
      verifiedOn,
      maintenanceMargin: 1.25,
      source: "https://hyperliquid.gitbook.io/hyperliquid-docs/trading/fees",
      sourceLabel: "Hyperliquid perps fee tiers",
      tiers: [{ id: "standard", label: "Base tier", maker: 0.015, taker: 0.045 }],
    },
    aster: {
      id: "aster",
      name: "Aster USDT Perp",
      settlement: "USDT",
      verifiedOn,
      maintenanceMargin: 0.5,
      source: "https://docs.asterdex.com/trading/perpetuals/fees-and-specs/fees",
      sourceLabel: "Aster USDT perpetual fees",
      tiers: [
        { id: "standard", label: "Standard", maker: 0, taker: 0.04 },
        { id: "aster-token", label: "Pay with ASTER (5% discount)", maker: 0, taker: 0.038 },
      ],
    },
    lighter: {
      id: "lighter",
      name: "Lighter Perps",
      settlement: "USDC",
      verifiedOn,
      maintenanceMargin: 0.5,
      source: "https://docs.lighter.xyz/trading/trading-fees",
      sourceLabel: "Lighter trading fees",
      tiers: [
        { id: "standard", label: "Standard account", maker: 0, taker: 0 },
        { id: "premium", label: "Premium — no LIT staked", maker: 0.004, taker: 0.028 },
      ],
    },
    custom: {
      id: "custom",
      name: "Custom / Manual",
      settlement: "USDT",
      verifiedOn,
      maintenanceMargin: 0.5,
      source: "",
      sourceLabel: "Manual rates",
      tiers: [{ id: "custom", label: "Custom rates", maker: 0.02, taker: 0.05 }],
    },
  };
})();
